namespace CrowLink.Services.Mobile;

internal static class MobileWebAssets
{
    public static string Html(string pcName) => """
<!doctype html>
<html lang="ko">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover">
<meta name="theme-color" content="#07151d"><title>CrowLink Mobile Touchpad</title>
<style>
:root{color-scheme:dark;--sky:#69d4ff;--ink:#eaf9ff;--muted:#8fb2c2;--line:#214251;--green:#66efaf;--red:#ff6472}*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}html,body{margin:0;width:100%;height:100%;overflow:hidden;overscroll-behavior:none;background:#061017;color:var(--ink);font-family:system-ui,-apple-system,"Segoe UI",sans-serif;user-select:none}body{display:grid;grid-template-rows:auto 1fr auto;padding:max(10px,env(safe-area-inset-top)) max(10px,env(safe-area-inset-right)) max(10px,env(safe-area-inset-bottom)) max(10px,env(safe-area-inset-left));gap:9px;background:radial-gradient(circle at 80% 0,#123646 0,transparent 42%),#061017}header{display:flex;align-items:center;justify-content:space-between}.brand{font-weight:800;letter-spacing:.4px}.pc{font-size:11px;color:var(--muted)}#status{display:flex;align-items:center;gap:7px;font-size:12px;padding:7px 10px;border:1px solid var(--line);border-radius:999px;color:#ffd57a;background:#13232b}#status:before{content:"";width:8px;height:8px;border-radius:50%;background:#ffd57a}.connected #status{color:var(--green);border-color:#287456}.connected #status:before{background:var(--green);animation:pulse 1s ease-in-out infinite}.connecting #status:before{animation:pulse .75s ease-in-out infinite}@keyframes pulse{50%{opacity:.18;box-shadow:0 0 14px currentColor}}
#pad{position:relative;min-height:0;border:1px solid var(--line);border-radius:20px;overflow:hidden;touch-action:none;background:linear-gradient(145deg,#0c202b,#08161e);box-shadow:inset 0 0 60px #0d2b38,0 12px 50px #0008}#pad:before{content:"TOUCHPAD";position:absolute;inset:0;display:grid;place-items:center;font-size:12px;letter-spacing:4px;color:#69d4ff55}.pen #pad:before{content:"PEN · 1:1 SCREEN MAP"}.pen #pad{background:#09151c}.pen-zone{position:absolute;border:1px solid #69d4ff88;background:#102b38;box-shadow:inset 0 0 34px #69d4ff18;pointer-events:none;display:none}.pen .pen-zone{display:block}.orientation{display:none;position:absolute;z-index:4;inset:auto 14px 54px;padding:10px;border-radius:10px;background:#241f10e8;color:#ffe08c;text-align:center;font-size:12px}.pen.portrait .orientation{display:block}.toolbar{position:absolute;z-index:3;top:9px;left:9px;right:9px;display:flex;align-items:center;gap:7px;padding:7px;border:1px solid #214251;border-radius:13px;background:#07151de8;backdrop-filter:blur(8px)}button,select,input{font:inherit}.toolbar button{padding:7px 10px}.toolbar button.active{background:var(--sky);color:#06202c}.toolbar label{display:flex;align-items:center;gap:5px;font-size:10px;color:var(--muted)}#sensitivity{width:min(26vw,120px)}#monitor{min-width:0;max-width:132px;padding:7px;border:1px solid #31596a;border-radius:9px;background:#0b202a;color:var(--ink)}
#pair{position:fixed;z-index:20;inset:0;display:grid;place-items:center;background:#061017f5;padding:24px;touch-action:auto;user-select:text}.is-hidden{display:none!important}.card{width:min(340px,100%);padding:22px;border:1px solid var(--line);border-radius:18px;background:#0b1c25;box-shadow:0 20px 70px #000b}.card h1{font-size:20px;margin:0 0 6px}.card p{font-size:13px;color:var(--muted);line-height:1.5}.card input{width:100%;font-size:24px;letter-spacing:8px;text-align:center;padding:13px;border-radius:11px;border:1px solid #31596a;background:#061118;color:var(--ink);touch-action:manipulation;user-select:text}.card input:focus{outline:2px solid var(--sky);border-color:transparent}.card button{width:100%;margin-top:10px;background:var(--sky);color:#06202c;border-color:#9ae5ff}button{border:1px solid #2a6077;border-radius:11px;background:#12384a;color:var(--ink);font-weight:700;padding:12px;touch-action:manipulation}.buttons{display:grid;grid-template-columns:1fr 1fr auto;gap:8px}.buttons button{min-height:47px}.stop{min-width:74px;color:#687985;border-color:#243842;background:#101b21}.connected .stop{color:#fff;border-color:#ff7b85;background:#c73c49;box-shadow:0 0 16px #ff526044}.stop:disabled{opacity:.55}.hint{position:absolute;bottom:13px;left:0;right:0;text-align:center;color:var(--muted);font-size:11px;pointer-events:none}.ended{position:absolute;z-index:5;inset:0;display:grid;place-items:center;background:#071119e8;text-align:center;padding:25px}.ended strong{display:block;margin-bottom:7px;color:#ff9ba1}.ended span{font-size:12px;color:var(--muted)}
@media(max-width:520px){.toolbar{flex-wrap:wrap}.toolbar label{flex:1}.toolbar #monitor{flex:1}.pc{max-width:56vw;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}}@media(orientation:landscape){body{grid-template-columns:1fr auto;grid-template-rows:auto 1fr}header{grid-column:1/-1}.buttons{grid-column:2;grid-row:2;grid-template-columns:66px;grid-template-rows:1fr 1fr auto}.buttons button{padding:8px}.stop{min-width:66px}}
.toolbar{position:static;grid-area:tools;flex-wrap:wrap;align-content:start;max-width:160px}.pen .hint{display:none}.orientation{position:static;inset:auto;margin-top:10px}#pad{grid-area:pad}header{grid-area:header}.buttons{grid-area:buttons}body{grid-template-areas:"header header" "pad tools" "buttons buttons";grid-template-columns:minmax(0,1fr) 150px;grid-template-rows:auto minmax(0,1fr) auto}.pen-zone{background-size:100% 100%;background-repeat:no-repeat}.toolbar #monitor{max-width:100%;width:100%}#sensitivity{width:100px}@media(orientation:landscape){body{grid-template-areas:"header header header" "pad tools buttons";grid-template-columns:minmax(0,1fr) 150px 66px;grid-template-rows:auto minmax(0,1fr)}}
.toolbar{overflow-y:auto}.toolbar select{max-width:100%;background:#102632;color:#eaf9ff;border:1px solid #31596a;border-radius:8px;padding:6px}.toolbar input[type=range]{max-width:100px}#inkColor{width:34px;height:28px;border:0;padding:0}.pen-option{display:none!important}.pen .pen-option{display:flex!important}.pen #tool{display:none}#toolStatus{font-size:11px;color:#ffd57a}.portrait-pen .orientation{display:none!important}@media(orientation:portrait){body{grid-template-areas:"header" "pad" "tools" "buttons";grid-template-columns:minmax(0,1fr);grid-template-rows:auto minmax(0,1fr) auto auto}#pad{min-height:180px;max-height:55vh}.toolbar{max-width:none;max-height:28vh;display:flex;flex-direction:row;gap:8px}.toolbar label{flex:0 1 auto}.toolbar #monitor{width:auto;flex:1 1 140px}.buttons{grid-template-columns:1fr 1fr auto}body.pen #pad{min-height:200px}header .pc{max-width:65vw}}
#phoneText{width:100%;min-width:0;min-height:50px;background:#0d202a;color:#fff;border:1px solid #31596a;border-radius:7px;user-select:text;touch-action:auto}#browserCursor{position:absolute;width:15px;height:15px;border:2px solid #fff;border-radius:50%;background:#ff4477;pointer-events:none;z-index:10;display:none}
.keyboardTools{width:100%;font-size:12px}.keyboardTools summary{cursor:pointer;padding:6px}.keyboardTools textarea{margin:6px 0}@media(orientation:portrait){body{grid-template-rows:auto auto minmax(0,1fr) auto}#pad{aspect-ratio:1/1;height:auto;max-height:48vh}.toolbar{min-height:0;max-height:none;align-content:start}body.pen #pad{min-height:180px}}
.pen-zone{background-color:#102330;background-image:linear-gradient(to right,transparent calc(33.333% - .5px),#a6bec12b 33.333%,transparent calc(33.333% + .5px),transparent calc(66.666% - .5px),#a6bec12b 66.666%,transparent calc(66.666% + .5px)),linear-gradient(to bottom,transparent calc(33.333% - .5px),#a6bec12b 33.333%,transparent calc(33.333% + .5px),transparent calc(66.666% - .5px),#a6bec12b 66.666%,transparent calc(66.666% + .5px))}.pen-zone:after{content:"+";position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);color:#9bb1b566;font-size:20px}#localInk{position:absolute;inset:0;width:100%;height:100%;overflow:hidden}#guideLabel{position:absolute;left:6px;top:4px;font-size:10px;color:#b3cbd1;opacity:.6}.whiteboard .pen-zone{background-color:#fff}.whiteboard #guideLabel{color:#333}#whiteboard[aria-pressed=true]{background:#fff;color:#17202b}#openExchange{padding:4px 8px;font-size:11px;margin-bottom:3px}#exchange{position:fixed;inset:0;z-index:15;background:#061017f5;padding:15px;overflow:auto;user-select:text;touch-action:auto}.exchange-card{max-width:700px;margin:auto}.exchange-head,.exchange-actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.exchange-head{justify-content:space-between}.exchange-card p{font-size:12px;color:var(--muted)}.shared-area{position:relative}#phoneText{height:32vh;resize:vertical}#sharedImage{display:block;max-width:100%;max-height:30vh;object-fit:contain;margin:10px auto}.image-picker{border:1px solid #31596a;padding:10px;border-radius:10px;font-size:12px}.image-picker input{max-width:200px}.exchange-actions button{font-size:12px;padding:9px}.exchange-actions a{color:var(--sky)}
.inkActions{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:5px;width:100%;align-self:end}.toolbar .inkActions button{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;padding:7px 2px;min-width:0}.inkActions svg{width:22px;height:22px;fill:none;stroke:currentColor;stroke-width:1.6;stroke-linecap:round;stroke-linejoin:round}.inkActions span{font-size:9px;white-space:nowrap;font-weight:500}.inkActions button:disabled{opacity:.4}
</style></head>
<body><header><div><div class="brand">CrowLink __CROWLINK_VERSION__</div><div class="pc">__CROWLINK_PC_NAME__ · Mobile Touchpad</div></div><div><button id="openExchange">텍스트·클립보드</button><div id="status">연결 안 됨</div></div></header>
<div class="toolbar"><button id="touchMode" class="active">터치패드</button><button id="penMode">펜</button><label>감도 <input id="sensitivity" type="range" min="0.5" max="5" step="0.1" value="1.6"></label><label><input id="acceleration" type="checkbox" checked> 가속</label><select id="monitor" class="is-hidden" aria-label="펜 대상 화면"></select><label><input id="rotationLock" type="checkbox"> 고정</label><label class="pen-option"><input id="portraitPen" type="checkbox"> 세로화면</label><select id="tool" aria-label="포인터 도구"><option value="cursor">일반 포인터</option><option value="laser">레이저 포인터</option><option value="highlight">형광펜</option><option value="wand">╱ 지시봉</option><option value="finger">☝ 검지 손가락</option></select><label>색 <input id="inkColor" type="color" value="#ff3030"></label><label>굵기 <input id="inkWidth" type="range" min="1" max="20" value="4"></label><div class="inkActions"><button id="clearInk" ><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 14 13 4l7 7-10 10H6l-4-4 2-3Zm5 4 7-7M10 21h11"/></svg><span>지우기</span></button><button id="capture" ><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 7h5l2-3h4l2 3h5v14H3ZM16 14a4 4 0 1 0-8 0 4 4 0 0 0 8 0"/></svg><span>화면 캡처</span></button><button id="whiteboard" aria-pressed="false" disabled title="펜 모드에서 사용"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 3h18v14H3ZM12 17v5M7 22h10"/></svg><span>화이트보드</span></button></div><span id="toolStatus" role="status"></span><div class="orientation">펜 모드는 휴대폰을 가로 방향으로 사용하면 더 정확합니다.</div></div><main id="pad"><div id="penZone" class="pen-zone"><svg id="localInk" viewBox="0 0 1000 1000" preserveAspectRatio="none"></svg><span id="guideLabel"></span></div><div id="ended" class="ended is-hidden"><div><strong>연결이 종료되었습니다.</strong><span>PC의 모바일 서버도 자동으로 중지되었습니다.<br>다시 사용하려면 PC에서 서버를 시작하세요.</span></div></div><div class="hint">터치패드: 이동·탭·두 손가락 스크롤 · 펜: PC 화면과 절대좌표 매칭</div></main>
<footer class="buttons"><button id="left">LEFT</button><button id="right">RIGHT</button><button id="stop" class="stop" disabled>중지</button></footer>
<section id="pair"><div class="card"><h1>휴대폰 연결</h1><p>PC의 Mobile 화면에 표시된 6자리 코드를 입력하세요. 연결 요청과 전체화면 시작은 한 번에 처리됩니다.</p><input id="code" type="text" inputmode="numeric" pattern="[0-9]*" maxlength="6" autocomplete="one-time-code" enterkeyhint="go" placeholder="000000"><button id="connect">연결하고 전체화면 시작</button></div></section>
<section id="exchange" class="is-hidden" aria-label="텍스트·클립보드"><div class="exchange-card"><div class="exchange-head"><strong>텍스트·클립보드</strong><button id="closeExchange">닫기</button></div><p>PC 키보드 연동 내용이 여기에 표시됩니다. 복사한 뒤 원하는 앱에 붙여넣으세요.</p><div class="shared-area"><div id="browserCursor"></div><textarea id="phoneText" maxlength="100000" placeholder="PC에서 받은 글 / PC로 보낼 글"></textarea></div><div class="exchange-actions"><button id="sendSharedText">PC로 텍스트 보내기</button><button id="copySharedText">텍스트 복사</button><label class="image-picker">이미지 선택<input id="sharedFile" type="file" accept="image/*"></label></div><img id="sharedImage" alt="교환한 이미지" class="is-hidden"><div class="exchange-actions"><button id="copySharedImage">이미지 복사</button><a id="saveSharedImage" download="CrowLink.png" class="is-hidden">이미지 저장</a></div><p id="exchangeStatus" role="status"></p></div></section>
<script>
(()=>{'use strict';
const body=document.body,pad=document.querySelector('#pad'),pair=document.querySelector('#pair'),ended=document.querySelector('#ended'),statusEl=document.querySelector('#status'),code=document.querySelector('#code'),stop=document.querySelector('#stop'),monitor=document.querySelector('#monitor'),sensitivity=document.querySelector('#sensitivity'),acceleration=document.querySelector('#acceleration'),penZone=document.querySelector('#penZone');
let ws=null,session='',mode='touchpad',monitors=[],active=new Map(),pendingX=0,pendingY=0,pendingScroll=0,pendingHorizontal=0,raf=0,lastTapAt=0,lastTapPoint=null,dragging=false,dragArmed=false,twoStart=0,twoMoved=false,lastCenter=null,scrollAxis=null,scrollX=0,scrollY=0,longTimer=0,penPointer=null,wasPaired=false,localStroke=null,inkPoints=[],whiteboard=false,textRevision=-1;
const send=o=>{if(ws&&ws.readyState===1&&session){o.session=session;o.clientTime=Date.now();ws.send(JSON.stringify(o));}};
function state(kind,text){body.classList.remove('connecting','connected');if(kind)body.classList.add(kind);statusEl.textContent=text;stop.disabled=kind!=='connected'}
async function enterFullscreen(){try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen({navigationUI:'hide'})}catch{}}
async function leaveFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen()}catch{}try{screen.orientation?.unlock()}catch{}}
async function wake(){try{if('wakeLock'in navigator)await navigator.wakeLock.request('screen')}catch{}}
function deviceName(){return navigator.userAgent.includes('iPhone')?'iPhone Browser':navigator.userAgent.includes('Android')?'Android Browser':'Mobile Browser'}
async function connect(){const value=code.value.replace(/\D/g,'');code.value=value;if(value.length!==6){state('','6자리 코드 필요');code.focus();return}await enterFullscreen();pair.classList.add('is-hidden');ended.classList.add('is-hidden');const scheme=location.protocol==='https:'?'wss':'ws';ws=new WebSocket(`${scheme}://${location.host}/ws`);state('connecting','연결 중…');ws.onopen=()=>ws.send(JSON.stringify({type:'hello',code:value,name:deviceName()}));ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='paired'){session=m.session;wasPaired=true;monitors=Array.isArray(m.monitors)?m.monitors:[];sensitivity.value=m.sensitivity||1.6;acceleration.checked=m.acceleration!==false;fillMonitors(m.monitorIndex||0);state('connected','연결됨');wake();sendSettings();updatePenZone()}else if(m.type==='browserText'){if((m.revision??0)>=textRevision){textRevision=m.revision??0;document.querySelector('#phoneText').value=m.text;exchangeMessage('PC에서 텍스트를 받았습니다.');document.querySelector('#exchange').classList.remove('is-hidden')}}else if(m.type==='browserImage'){showSharedImage(m.png);exchangeMessage('PC에서 이미지를 받았습니다.');document.querySelector('#exchange').classList.remove('is-hidden')}else if(m.type==='browserPointer'){const cursor=document.querySelector('#browserCursor');cursor.style.display='block';cursor.style.left=(Math.max(0,Math.min(1,m.x))*100)+'%';cursor.style.top=(Math.max(0,Math.min(1,m.y))*100)+'%';if(m.click){document.querySelector('#exchange').classList.remove('is-hidden');document.querySelector('#phoneText').focus()}}else if(m.type==='captured'){document.querySelector('#toolStatus').textContent='PC에 저장: '+m.filename}else if(m.type==='whiteboard'){whiteboard=m.enabled;body.classList.toggle('whiteboard',whiteboard);document.querySelector('#whiteboard').setAttribute('aria-pressed',String(whiteboard))}else if(m.type==='shared'||m.type==='toolError'){exchangeMessage(m.message);document.querySelector('#toolStatus').textContent=m.message}else if(m.type==='error'){session='';pair.classList.remove('is-hidden');state('',m.message||'연결 실패');leaveFullscreen()}else if(m.type==='stopped'){finish('PC에서 연결 종료')}};ws.onclose=()=>finish(wasPaired?'연결 종료':'연결 끊김')}
function finish(text){release();clearLocalInk();whiteboard=false;body.classList.remove('whiteboard');session='';state('',text);if(wasPaired){ended.classList.remove('is-hidden');pair.classList.add('is-hidden')}else pair.classList.remove('is-hidden');leaveFullscreen()}
function fillMonitors(selected){monitor.textContent='';monitors.forEach((m,i)=>{const option=document.createElement('option');option.value=String(i);option.textContent=m.name||`화면 ${i+1}`;monitor.append(option)});monitor.value=String(Math.min(selected,Math.max(0,monitors.length-1)))}
function sendSettings(){send({type:'settings',mode,tool:document.querySelector('#tool').value,color:document.querySelector('#inkColor').value,width:Number(document.querySelector('#inkWidth').value),sensitivity:Number(sensitivity.value),acceleration:acceleration.checked,monitorIndex:Number(monitor.value||0)})}
async function setMode(next){release();if(mode!==next)clearLocalInk();mode=next;document.querySelector('#whiteboard').disabled=mode!=='pen';body.classList.toggle('pen',mode==='pen');document.querySelector('#touchMode').classList.toggle('active',mode==='touchpad');document.querySelector('#penMode').classList.toggle('active',mode==='pen');monitor.classList.toggle('is-hidden',mode!=='pen');release();sendSettings();updateOrientation();updatePenZone();if(mode==='pen'){await enterFullscreen();await applyOrientation()}else{applyOrientation()}}
function updateOrientation(){body.classList.toggle('portrait',mode==='pen'&&innerHeight>innerWidth)}
function penRect(){const bounds=pad.getBoundingClientRect(),bx=pad.clientLeft||0,by=pad.clientTop||0,r={left:bounds.left+bx,top:bounds.top+by,width:bounds.width-2*bx,height:bounds.height-2*by},m=monitors[Number(monitor.value||0)]||{width:16,height:9},ratio=m.width/Math.max(1,m.height);if(r.width/r.height>ratio){const width=r.height*ratio;return{left:r.left+(r.width-width)/2,top:r.top,width,height:r.height}}const height=r.width/ratio;return{left:r.left,top:r.top+(r.height-height)/2,width:r.width,height}}
function updatePenZone(){if(mode!=='pen')return;const r=penRect(),p=pad.getBoundingClientRect();penZone.style.left=(r.left-p.left-(pad.clientLeft||0))+'px';penZone.style.top=(r.top-p.top-(pad.clientTop||0))+'px';penZone.style.width=r.width+'px';penZone.style.height=r.height+'px';const m=monitors[Number(monitor.value||0)];document.querySelector('#guideLabel').textContent=m?`화면 ${Number(monitor.value||0)+1} · ${m.width}×${m.height}`:'3×3 위치 가이드'}
function sendPen(e,phase){const r=penRect(),x=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));if(phase==='down'){const svg=document.querySelector('#localInk');if(svg.children.length>=2000)svg.removeChild(svg.firstChild);localStroke=document.createElementNS('http://www.w3.org/2000/svg','polyline');inkPoints=[];localStroke.setAttribute('fill','none');localStroke.setAttribute('stroke',document.querySelector('#inkColor').value);localStroke.setAttribute('stroke-width',String(Number(document.querySelector('#inkWidth').value)*1000/(monitors[Number(monitor.value||0)]?.width||1920)));localStroke.setAttribute('stroke-linecap','round');localStroke.setAttribute('stroke-linejoin','round');svg.append(localStroke)}if(localStroke&&phase!=='cancel'){if(inkPoints.length<20000)inkPoints.push((x*1000).toFixed(2)+','+(y*1000).toFixed(2));localStroke.setAttribute('points',inkPoints.length===1?inkPoints[0]+' '+inkPoints[0]:inkPoints.join(' '))}if(phase==='up'||phase==='cancel')localStroke=null;send({type:'pen',x,y,phase})}
function clearLocalInk(){document.querySelector('#localInk').replaceChildren();localStroke=null;inkPoints=[];}
function schedule(){if(!raf)raf=requestAnimationFrame(()=>{raf=0;if(pendingX||pendingY)send({type:'move',dx:pendingX,dy:pendingY});if(pendingScroll||pendingHorizontal)send({type:'scroll',delta:pendingScroll,horizontal:pendingHorizontal});pendingX=pendingY=pendingScroll=pendingHorizontal=0})}function queue(dx,dy){pendingX+=dx;pendingY+=dy;schedule()}function queueScroll(dx,dy){scrollX+=dx;scrollY+=dy;if(!scrollAxis){if(Math.max(Math.abs(scrollX),Math.abs(scrollY))<6)return;scrollAxis=Math.abs(scrollY)>=Math.abs(scrollX)?'y':'x';dx=scrollX;dy=scrollY}twoMoved=true;if(scrollAxis==='y')pendingScroll-=dy*9;else pendingHorizontal+=dx*7;schedule()}function points(){return[...active.values()]}function center(ps){return{x:ps.reduce((s,p)=>s+p.x,0)/ps.length,y:ps.reduce((s,p)=>s+p.y,0)/ps.length}}
function release(){if(raf)cancelAnimationFrame(raf);raf=0;pendingX=pendingY=pendingScroll=pendingHorizontal=0;if(dragging)send({type:'button',button:'left',down:false});if(penPointer!==null)send({type:'pen',x:0,y:0,phase:'cancel'});penPointer=null;localStroke=null;scrollAxis=null;scrollX=scrollY=0;lastCenter=null;dragging=dragArmed=false;active.clear();clearTimeout(longTimer)}
pad.addEventListener('pointerdown',e=>{if(!session||e.target.closest('.toolbar'))return;e.preventDefault();pad.setPointerCapture(e.pointerId);if(mode==='pen'){const r=penRect();if(e.clientX<r.left||e.clientX>r.left+r.width||e.clientY<r.top||e.clientY>r.top+r.height)return;if(penPointer===null){penPointer=e.pointerId;sendPen(e,'down')}return}active.set(e.pointerId,{x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY,t:Date.now()});const ps=points();if(ps.length===1){const p=ps[0];if(Date.now()-lastTapAt<330&&lastTapPoint&&Math.hypot(p.x-lastTapPoint.x,p.y-lastTapPoint.y)<36){dragArmed=true;longTimer=setTimeout(()=>{if(dragArmed&&!dragging){dragging=true;send({type:'button',button:'left',down:true});navigator.vibrate?.(18)}},100)}else{dragArmed=false;longTimer=setTimeout(()=>{if(active.size===1&&!dragging){send({type:'click',button:'right'});active.get(e.pointerId).long=true;navigator.vibrate?.(22)}},620)}}else if(ps.length===2){pendingX=pendingY=0;scrollAxis=null;scrollX=scrollY=0;if(dragging){send({type:'button',button:'left',down:false});dragging=false}ps.forEach(p=>p.multi=true);dragArmed=false;clearTimeout(longTimer);twoStart=Date.now();twoMoved=false;lastCenter=center(ps)}});
pad.addEventListener('pointermove',e=>{if(mode==='pen'){if(e.pointerId===penPointer){e.preventDefault();const events=e.getCoalescedEvents?.()||[e];sendPen(events[events.length-1],'move')}return}const p=active.get(e.pointerId);if(!p)return;e.preventDefault();const ox=p.x,oy=p.y;p.x=e.clientX;p.y=e.clientY;const ps=points();if(ps.length===1){if(p.multi)return;const dist=Math.hypot(p.x-p.sx,p.y-p.sy);if(dragArmed&&dist>3&&!dragging){clearTimeout(longTimer);dragging=true;send({type:'button',button:'left',down:true});navigator.vibrate?.(18)}else if(dist>3&&!dragArmed)clearTimeout(longTimer);if(dragging||dist>1)queue(p.x-ox,p.y-oy)}else if(ps.length===2){const c=center(ps);if(lastCenter){const dx=c.x-lastCenter.x,dy=c.y-lastCenter.y;queueScroll(dx,dy)}lastCenter=c}});
function up(e){if(mode==='pen'){if(e.pointerId===penPointer){e.preventDefault();sendPen(e,e.type==='pointercancel'?'cancel':'up');penPointer=null}return}const p=active.get(e.pointerId);if(!p)return;e.preventDefault();if(e.type==='pointercancel'){release();return}clearTimeout(longTimer);const wasTwo=active.size===2;active.delete(e.pointerId);if(dragging){send({type:'button',button:'left',down:false});dragging=dragArmed=false;lastTapAt=0}else if(wasTwo){dragArmed=false;if(!twoMoved&&Date.now()-twoStart<300){send({type:'click',button:'right'});navigator.vibrate?.(20)}lastCenter=null}else if(!p.multi&&!p.long&&Date.now()-p.t<260&&Math.hypot(p.x-p.sx,p.y-p.sy)<8){dragArmed=false;send({type:'click',button:'left'});navigator.vibrate?.(12);lastTapAt=Date.now();lastTapPoint={x:p.x,y:p.y}}else dragArmed=false}
pad.addEventListener('pointerup',up);pad.addEventListener('pointercancel',up);for(const [id,button] of [['left','left'],['right','right']]){const el=document.querySelector('#'+id);el.addEventListener('pointerdown',e=>{if(!session)return;e.preventDefault();el.setPointerCapture(e.pointerId);send({type:'button',button,down:true});navigator.vibrate?.(12)});el.addEventListener('pointerup',e=>{e.preventDefault();send({type:'button',button,down:false})});el.addEventListener('pointercancel',()=>send({type:'button',button,down:false}))}
document.querySelector('#connect').addEventListener('click',connect);code.addEventListener('input',()=>code.value=code.value.replace(/\D/g,'').slice(0,6));code.addEventListener('keydown',e=>{if(e.key==='Enter')connect()});document.querySelector('#touchMode').addEventListener('click',()=>setMode('touchpad'));document.querySelector('#penMode').addEventListener('click',()=>setMode('pen'));sensitivity.addEventListener('input',sendSettings);acceleration.addEventListener('change',sendSettings);monitor.addEventListener('change',()=>{release();clearLocalInk();sendSettings();updatePenZone()});stop.addEventListener('click',()=>{send({type:'disconnect'});ws?.close();finish('사용자가 중지함')});pad.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('visibilitychange',()=>{if(document.hidden)release()});window.addEventListener('resize',()=>{release();updateOrientation();updatePenZone()});window.addEventListener('beforeunload',release);state('','연결 안 됨');
async function applyOrientation(){const lock=document.querySelector('#rotationLock'),portrait=document.querySelector('#portraitPen').checked;body.classList.toggle('portrait-pen',mode==='pen'&&portrait);try{if(mode==='pen'||lock.checked){if(!screen.orientation?.lock)throw Error();await screen.orientation.lock(mode==='pen'?(portrait?'portrait':'landscape'):(innerWidth>innerHeight?'landscape':'portrait'));document.querySelector('#toolStatus').textContent=''}else screen.orientation?.unlock()}catch{if(lock.checked){lock.checked=false;document.querySelector('#toolStatus').textContent='브라우저 고정 미지원 · 휴대폰 자동 회전을 꺼주세요.'}}updatePenZone()}
document.querySelector('#rotationLock').addEventListener('change',applyOrientation);document.querySelector('#portraitPen').addEventListener('change',applyOrientation);
for(const id of ['tool','inkColor','inkWidth'])document.querySelector('#'+id).addEventListener('change',sendSettings);
document.querySelector('#clearInk').addEventListener('click',()=>{clearLocalInk();send({type:'clearInk'})});document.querySelector('#capture').addEventListener('click',()=>send({type:'capture'}));
document.querySelector('#whiteboard').addEventListener('click',()=>send({type:'whiteboard',enabled:!whiteboard}));
const exchange=document.querySelector('#exchange'),phoneText=document.querySelector('#phoneText');
function exchangeMessage(message){document.querySelector('#exchangeStatus').textContent=message}
function requireSession(){if(session)return true;exchangeMessage('먼저 휴대폰을 연결하세요.');return false}
document.querySelector('#openExchange').addEventListener('click',()=>{release();exchange.classList.remove('is-hidden')});
document.querySelector('#closeExchange').addEventListener('click',()=>exchange.classList.add('is-hidden'));
document.querySelector('#sendSharedText').addEventListener('click',()=>{if(requireSession()){send({type:'shareText',text:phoneText.value});exchangeMessage('PC로 전송 중…')}});
document.querySelector('#copySharedText').addEventListener('click',async()=>{try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(phoneText.value);else{phoneText.focus();phoneText.select();if(!document.execCommand('copy'))throw Error()}exchangeMessage('텍스트를 복사했습니다.')}catch{phoneText.focus();phoneText.select();exchangeMessage('선택된 텍스트를 길게 눌러 복사하세요.')}});
let sharedPng='';
function showSharedImage(png){sharedPng=png;const img=document.querySelector('#sharedImage');img.src='data:image/png;base64,'+png;img.classList.remove('is-hidden');const link=document.querySelector('#saveSharedImage');link.href=img.src;link.classList.remove('is-hidden')}
async function sendImage(file){if(!file||!requireSession())return;try{if(file.size>12*1024*1024)throw Error('12MB 이하의 이미지를 선택하세요.');const url=URL.createObjectURL(file),img=new Image();try{img.src=url;await img.decode();const scale=Math.min(1,1600/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);const png=canvas.toDataURL('image/png').split(',')[1];if(png.length>2796204)throw Error('변환한 이미지가 2MB를 넘습니다. 더 작은 이미지를 선택하세요.');send({type:'shareImage',png});showSharedImage(png);exchangeMessage('이미지를 PC로 전송 중…')}finally{URL.revokeObjectURL(url)}}catch(error){exchangeMessage(error.message||'이미지를 읽지 못했습니다.')}}
document.querySelector('#sharedFile').addEventListener('change',e=>sendImage(e.target.files[0]));
phoneText.addEventListener('paste',e=>{const file=[...(e.clipboardData?.files||[])].find(f=>f.type.startsWith('image/'));if(file){e.preventDefault();sendImage(file)}});
document.querySelector('#copySharedImage').addEventListener('click',async()=>{try{if(!sharedPng)throw Error('수신된 이미지가 없습니다.');if(!navigator.clipboard?.write||typeof ClipboardItem==='undefined')throw Error('이 브라우저에서는 이미지 저장 후 원하는 앱에 첨부하세요.');const bytes=Uint8Array.from(atob(sharedPng),c=>c.charCodeAt(0));await navigator.clipboard.write([new ClipboardItem({'image/png':new Blob([bytes],{type:'image/png'})})]);exchangeMessage('이미지를 복사했습니다.')}catch(error){exchangeMessage(error.message||'이미지를 저장해 사용하세요.')}});

})();
</script></body></html>
""".Replace("__CROWLINK_PC_NAME__", Escape(pcName), StringComparison.Ordinal)
    .Replace("__CROWLINK_VERSION__", AppIdentity.Version.ToString(3), StringComparison.Ordinal);

    private static string Escape(string value) => value
        .Replace("&", "&amp;", StringComparison.Ordinal)
        .Replace("<", "&lt;", StringComparison.Ordinal)
        .Replace(">", "&gt;", StringComparison.Ordinal)
        .Replace("\"", "&quot;", StringComparison.Ordinal);
}
