namespace CrowLink.Services.Mobile;

internal static class MobileWebAssets
{
    public static string Html(string pcName) => """
<!doctype html>
<html lang="ko">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover">
<meta name="theme-color" content="#07151d"><title>CrowLink Mobile Touchpad</title>
<style>
:root{color-scheme:dark;--sky:#69d4ff;--ink:#eaf9ff;--muted:#8fb2c2;--line:#214251;--green:#66efaf;--red:#ff6472}*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}html,body{margin:0;width:100%;height:100%;overflow:hidden;overscroll-behavior:none;background:#061017;color:var(--ink);font-family:system-ui,-apple-system,"Segoe UI",sans-serif;user-select:none}body{display:grid;grid-template-rows:auto 1fr auto;padding:max(10px,env(safe-area-inset-top)) max(10px,env(safe-area-inset-right)) max(10px,env(safe-area-inset-bottom)) max(10px,env(safe-area-inset-left));gap:9px;background:radial-gradient(circle at 80% 0,#123646 0,transparent 42%),#061017}header{display:flex;align-items:center;justify-content:space-between}.brand{font-weight:800;letter-spacing:.4px}.pc{font-size:11px;color:var(--muted)}#status{display:flex;align-items:center;gap:7px;font-size:12px;padding:7px 10px;border:1px solid var(--line);border-radius:999px;color:#ffd57a;background:#13232b}#status:before{content:"";width:8px;height:8px;border-radius:50%;background:#ffd57a}.connected #status{color:var(--green);border-color:#287456}.connected #status:before{background:var(--green);animation:pulse 1s ease-in-out infinite}.connecting #status:before{animation:pulse .75s ease-in-out infinite}@keyframes pulse{50%{opacity:.18;box-shadow:0 0 14px currentColor}}
#pad{position:relative;min-height:0;border:1px solid var(--line);border-radius:20px;overflow:hidden;touch-action:none;background:linear-gradient(145deg,#0c202b,#08161e);box-shadow:inset 0 0 60px #0d2b38,0 12px 50px #0008}#pad:before{content:"TOUCHPAD";position:absolute;inset:0;display:grid;place-items:center;font-size:12px;letter-spacing:4px;color:#69d4ff55}.pen #pad:before{content:"PEN · 1:1 SCREEN MAP"}.pen #pad{background:#09151c}.pen-zone{position:absolute;border:1px solid #69d4ff88;background:#102b38;box-shadow:inset 0 0 34px #69d4ff18;pointer-events:none;display:none}.pen .pen-zone{display:block}.orientation{display:none;position:absolute;z-index:4;inset:auto 14px 54px;padding:10px;border-radius:10px;background:#241f10e8;color:#ffe08c;text-align:center;font-size:12px}.pen.portrait .orientation{display:block}.toolbar{position:absolute;z-index:3;top:9px;left:9px;right:9px;display:flex;align-items:center;gap:7px;padding:7px;border:1px solid #214251;border-radius:13px;background:#07151de8;backdrop-filter:blur(8px)}button,select,input{font:inherit}.toolbar button{padding:7px 10px}.toolbar button.active{background:var(--sky);color:#06202c}.toolbar label{display:flex;align-items:center;gap:5px;font-size:10px;color:var(--muted)}#sensitivity{width:min(26vw,120px)}#monitor{min-width:0;max-width:132px;padding:7px;border:1px solid #31596a;border-radius:9px;background:#0b202a;color:var(--ink)}
#pair{position:fixed;z-index:20;inset:0;display:grid;place-items:center;background:#061017f5;padding:24px;touch-action:auto;user-select:text}.is-hidden{display:none!important}.card{width:min(340px,100%);padding:22px;border:1px solid var(--line);border-radius:18px;background:#0b1c25;box-shadow:0 20px 70px #000b}.card h1{font-size:20px;margin:0 0 6px}.card p{font-size:13px;color:var(--muted);line-height:1.5}.card input{width:100%;font-size:24px;letter-spacing:8px;text-align:center;padding:13px;border-radius:11px;border:1px solid #31596a;background:#061118;color:var(--ink);touch-action:manipulation;user-select:text}.card input:focus{outline:2px solid var(--sky);border-color:transparent}.card button{width:100%;margin-top:10px;background:var(--sky);color:#06202c;border-color:#9ae5ff}button{border:1px solid #2a6077;border-radius:11px;background:#12384a;color:var(--ink);font-weight:700;padding:12px;touch-action:manipulation}.buttons{display:grid;grid-template-columns:1fr 1fr auto;gap:8px}.buttons button{min-height:47px}.stop{min-width:74px;color:#687985;border-color:#243842;background:#101b21}.connected .stop{color:#fff;border-color:#ff7b85;background:#c73c49;box-shadow:0 0 16px #ff526044}.stop:disabled{opacity:.55}.hint{position:absolute;bottom:13px;left:0;right:0;text-align:center;color:var(--muted);font-size:11px;pointer-events:none}.ended{position:absolute;z-index:5;inset:0;display:grid;place-items:center;background:#071119e8;text-align:center;padding:25px}.ended strong{display:block;margin-bottom:7px;color:#ff9ba1}.ended span{font-size:12px;color:var(--muted)}
@media(max-width:520px){.toolbar{flex-wrap:wrap}.toolbar label{flex:1}.toolbar #monitor{flex:1}.pc{max-width:56vw;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}}@media(orientation:landscape){body{grid-template-columns:1fr auto;grid-template-rows:auto 1fr}header{grid-column:1/-1}.buttons{grid-column:2;grid-row:2;grid-template-columns:66px;grid-template-rows:1fr 1fr auto}.buttons button{padding:8px}.stop{min-width:66px}}
</style></head>
<body><header><div><div class="brand">CrowLink 1.5</div><div class="pc">__CROWLINK_PC_NAME__ · Mobile Touchpad</div></div><div id="status">연결 안 됨</div></header>
<main id="pad"><div class="toolbar"><button id="touchMode" class="active">터치패드</button><button id="penMode">펜</button><label>감도 <input id="sensitivity" type="range" min="0.5" max="5" step="0.1" value="1.6"></label><label><input id="acceleration" type="checkbox" checked> 가속</label><select id="monitor" class="is-hidden" aria-label="펜 대상 화면"></select></div><div id="penZone" class="pen-zone"></div><div class="orientation">펜 모드는 휴대폰을 가로 방향으로 사용하면 더 정확합니다.</div><div id="ended" class="ended is-hidden"><div><strong>연결이 종료되었습니다.</strong><span>PC의 모바일 서버도 자동으로 중지되었습니다.<br>다시 사용하려면 PC에서 서버를 시작하세요.</span></div></div><div class="hint">터치패드: 이동·탭·두 손가락 스크롤 · 펜: PC 화면과 절대좌표 매칭</div></main>
<footer class="buttons"><button id="left">LEFT</button><button id="right">RIGHT</button><button id="stop" class="stop" disabled>중지</button></footer>
<section id="pair"><div class="card"><h1>휴대폰 연결</h1><p>PC의 Mobile 화면에 표시된 6자리 코드를 입력하세요. 연결 요청과 전체화면 시작은 한 번에 처리됩니다.</p><input id="code" type="text" inputmode="numeric" pattern="[0-9]*" maxlength="6" autocomplete="one-time-code" enterkeyhint="go" placeholder="000000"><button id="connect">연결하고 전체화면 시작</button></div></section>
<script>
(()=>{'use strict';
const body=document.body,pad=document.querySelector('#pad'),pair=document.querySelector('#pair'),ended=document.querySelector('#ended'),statusEl=document.querySelector('#status'),code=document.querySelector('#code'),stop=document.querySelector('#stop'),monitor=document.querySelector('#monitor'),sensitivity=document.querySelector('#sensitivity'),acceleration=document.querySelector('#acceleration'),penZone=document.querySelector('#penZone');
let ws=null,session='',mode='touchpad',monitors=[],active=new Map(),pendingX=0,pendingY=0,pendingScroll=0,pendingHorizontal=0,raf=0,lastTapAt=0,lastTapPoint=null,dragging=false,dragArmed=false,twoStart=0,twoMoved=false,lastCenter=null,longTimer=0,penPointer=null,wasPaired=false;
const send=o=>{if(ws&&ws.readyState===1&&session){o.session=session;o.clientTime=Date.now();ws.send(JSON.stringify(o));}};
function state(kind,text){body.classList.remove('connecting','connected');if(kind)body.classList.add(kind);statusEl.textContent=text;stop.disabled=kind!=='connected'}
async function enterFullscreen(){try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen({navigationUI:'hide'})}catch{}}
async function leaveFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen()}catch{}try{screen.orientation?.unlock()}catch{}}
async function wake(){try{if('wakeLock'in navigator)await navigator.wakeLock.request('screen')}catch{}}
function deviceName(){return navigator.userAgent.includes('iPhone')?'iPhone Browser':navigator.userAgent.includes('Android')?'Android Browser':'Mobile Browser'}
async function connect(){const value=code.value.replace(/\D/g,'');code.value=value;if(value.length!==6){state('','6자리 코드 필요');code.focus();return}await enterFullscreen();pair.classList.add('is-hidden');ended.classList.add('is-hidden');const scheme=location.protocol==='https:'?'wss':'ws';ws=new WebSocket(`${scheme}://${location.host}/ws`);state('connecting','연결 중…');ws.onopen=()=>ws.send(JSON.stringify({type:'hello',code:value,name:deviceName()}));ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='paired'){session=m.session;wasPaired=true;monitors=Array.isArray(m.monitors)?m.monitors:[];sensitivity.value=m.sensitivity||1.6;acceleration.checked=m.acceleration!==false;fillMonitors(m.monitorIndex||0);state('connected','연결됨');wake();sendSettings();updatePenZone()}else if(m.type==='error'){session='';pair.classList.remove('is-hidden');state('',m.message||'연결 실패');leaveFullscreen()}else if(m.type==='stopped'){finish('PC에서 연결 종료')}};ws.onclose=()=>finish(wasPaired?'연결 종료':'연결 끊김')}
function finish(text){release();session='';state('',text);if(wasPaired){ended.classList.remove('is-hidden');pair.classList.add('is-hidden')}else pair.classList.remove('is-hidden');leaveFullscreen()}
function fillMonitors(selected){monitor.textContent='';monitors.forEach((m,i)=>{const option=document.createElement('option');option.value=String(i);option.textContent=m.name||`화면 ${i+1}`;monitor.append(option)});monitor.value=String(Math.min(selected,Math.max(0,monitors.length-1)))}
function sendSettings(){send({type:'settings',mode,sensitivity:Number(sensitivity.value),acceleration:acceleration.checked,monitorIndex:Number(monitor.value||0)})}
function setMode(next){mode=next;body.classList.toggle('pen',mode==='pen');document.querySelector('#touchMode').classList.toggle('active',mode==='touchpad');document.querySelector('#penMode').classList.toggle('active',mode==='pen');monitor.classList.toggle('is-hidden',mode!=='pen');release();sendSettings();updateOrientation();updatePenZone();if(mode==='pen'){enterFullscreen();try{screen.orientation?.lock('landscape').catch(()=>{})}catch{}}else{try{screen.orientation?.unlock()}catch{}}}
function updateOrientation(){body.classList.toggle('portrait',mode==='pen'&&innerHeight>innerWidth)}
function penRect(){const r=pad.getBoundingClientRect(),m=monitors[Number(monitor.value||0)]||{width:16,height:9},ratio=m.width/Math.max(1,m.height);if(r.width/r.height>ratio){const width=r.height*ratio;return{left:r.left+(r.width-width)/2,top:r.top,width,height:r.height}}const height=r.width/ratio;return{left:r.left,top:r.top+(r.height-height)/2,width:r.width,height}}
function updatePenZone(){if(mode!=='pen')return;const r=penRect(),p=pad.getBoundingClientRect();penZone.style.left=(r.left-p.left)+'px';penZone.style.top=(r.top-p.top)+'px';penZone.style.width=r.width+'px';penZone.style.height=r.height+'px'}
function sendPen(e,phase){const r=penRect(),x=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));send({type:'pen',x,y,phase})}
function schedule(){if(!raf)raf=requestAnimationFrame(()=>{raf=0;if(pendingX||pendingY)send({type:'move',dx:pendingX,dy:pendingY});if(pendingScroll||pendingHorizontal)send({type:'scroll',delta:pendingScroll,horizontal:pendingHorizontal});pendingX=pendingY=pendingScroll=pendingHorizontal=0})}function queue(dx,dy){pendingX+=dx;pendingY+=dy;schedule()}function queueScroll(dx,dy){pendingScroll+=-dy*9;pendingHorizontal+=dx*7;schedule()}function points(){return[...active.values()]}function center(ps){return{x:ps.reduce((s,p)=>s+p.x,0)/ps.length,y:ps.reduce((s,p)=>s+p.y,0)/ps.length}}
function release(){if(dragging)send({type:'button',button:'left',down:false});if(penPointer!==null)send({type:'pen',x:0,y:0,phase:'cancel'});penPointer=null;dragging=dragArmed=false;active.clear();clearTimeout(longTimer)}
pad.addEventListener('pointerdown',e=>{if(!session||e.target.closest('.toolbar'))return;e.preventDefault();pad.setPointerCapture(e.pointerId);if(mode==='pen'){if(penPointer===null){penPointer=e.pointerId;sendPen(e,'down')}return}active.set(e.pointerId,{x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY,t:Date.now()});const ps=points();if(ps.length===1){const p=ps[0];if(Date.now()-lastTapAt<330&&lastTapPoint&&Math.hypot(p.x-lastTapPoint.x,p.y-lastTapPoint.y)<36){dragArmed=true;longTimer=setTimeout(()=>{if(dragArmed&&!dragging){dragging=true;send({type:'button',button:'left',down:true});navigator.vibrate?.(18)}},100)}else{dragArmed=false;longTimer=setTimeout(()=>{if(active.size===1&&!dragging){send({type:'click',button:'right'});active.get(e.pointerId).long=true;navigator.vibrate?.(22)}},620)}}else if(ps.length===2){dragArmed=false;clearTimeout(longTimer);twoStart=Date.now();twoMoved=false;lastCenter=center(ps)}});
pad.addEventListener('pointermove',e=>{if(mode==='pen'){if(e.pointerId===penPointer){e.preventDefault();const events=e.getCoalescedEvents?.()||[e];sendPen(events[events.length-1],'move')}return}const p=active.get(e.pointerId);if(!p)return;e.preventDefault();const ox=p.x,oy=p.y;p.x=e.clientX;p.y=e.clientY;const ps=points();if(ps.length===1){const dist=Math.hypot(p.x-p.sx,p.y-p.sy);if(dragArmed&&dist>3&&!dragging){clearTimeout(longTimer);dragging=true;send({type:'button',button:'left',down:true});navigator.vibrate?.(18)}else if(dist>3&&!dragArmed)clearTimeout(longTimer);if(dragging||dist>1)queue(p.x-ox,p.y-oy)}else if(ps.length===2){const c=center(ps);if(lastCenter){const dx=c.x-lastCenter.x,dy=c.y-lastCenter.y;if(Math.abs(dx)+Math.abs(dy)>1.5){twoMoved=true;queueScroll(dx,dy)}}lastCenter=c}});
function up(e){if(mode==='pen'){if(e.pointerId===penPointer){e.preventDefault();sendPen(e,e.type==='pointercancel'?'cancel':'up');penPointer=null}return}const p=active.get(e.pointerId);if(!p)return;e.preventDefault();clearTimeout(longTimer);const wasTwo=active.size===2;active.delete(e.pointerId);if(dragging){send({type:'button',button:'left',down:false});dragging=dragArmed=false;lastTapAt=0}else if(wasTwo){dragArmed=false;if(!twoMoved&&Date.now()-twoStart<300){send({type:'click',button:'right'});navigator.vibrate?.(20)}lastCenter=null}else if(!p.long&&Date.now()-p.t<260&&Math.hypot(p.x-p.sx,p.y-p.sy)<8){dragArmed=false;send({type:'click',button:'left'});navigator.vibrate?.(12);lastTapAt=Date.now();lastTapPoint={x:p.x,y:p.y}}else dragArmed=false}
pad.addEventListener('pointerup',up);pad.addEventListener('pointercancel',up);for(const [id,button] of [['left','left'],['right','right']]){const el=document.querySelector('#'+id);el.addEventListener('pointerdown',e=>{if(!session)return;e.preventDefault();send({type:'button',button,down:true});navigator.vibrate?.(12)});el.addEventListener('pointerup',e=>{e.preventDefault();send({type:'button',button,down:false})});el.addEventListener('pointercancel',()=>send({type:'button',button,down:false}))}
document.querySelector('#connect').addEventListener('click',connect);code.addEventListener('input',()=>code.value=code.value.replace(/\D/g,'').slice(0,6));code.addEventListener('keydown',e=>{if(e.key==='Enter')connect()});document.querySelector('#touchMode').addEventListener('click',()=>setMode('touchpad'));document.querySelector('#penMode').addEventListener('click',()=>setMode('pen'));sensitivity.addEventListener('input',sendSettings);acceleration.addEventListener('change',sendSettings);monitor.addEventListener('change',()=>{sendSettings();updatePenZone()});stop.addEventListener('click',()=>{send({type:'disconnect'});ws?.close();finish('사용자가 중지함')});document.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('visibilitychange',()=>{if(document.hidden)release()});window.addEventListener('resize',()=>{updateOrientation();updatePenZone()});window.addEventListener('beforeunload',release);state('','연결 안 됨');
})();
</script></body></html>
""".Replace("__CROWLINK_PC_NAME__", Escape(pcName), StringComparison.Ordinal);

    private static string Escape(string value) => value
        .Replace("&", "&amp;", StringComparison.Ordinal)
        .Replace("<", "&lt;", StringComparison.Ordinal)
        .Replace(">", "&gt;", StringComparison.Ordinal)
        .Replace("\"", "&quot;", StringComparison.Ordinal);
}
